blog/urls.py
from django.urls import path
from .views import blog, detail


app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('<int:blog_id>', detail, name='detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('projects/', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from portfolio.models import Portfolio
from .views import index, detail


app_name = 'project'

urlpatterns = [
    path('', index, name='project'),
    path('<int:project_id>', detail, name='project_detail'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from distutils.command.upload import upload
from operator import mod
from django.db import models
from django.test import modify_settings


class Portfolio(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/index.html', {'blogs': blogs})

def detail(request, blog_id):
    detail = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'detail': detail})

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Portfolio


def index(request):
    projects = Portfolio.objects.all()
    return render(request, 'portfolio/index.html', {'projects': projects})


def detail(request, project_id):
    project_detail = get_object_or_404(Portfolio, pk=project_id)
    return render(request, 'portfolio/detail.html', {'detail': project_detail})

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>My Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand ms-5" href="#">Berzezek</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blog' %}">Blogs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project:project' %}">Projects</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">№ {{ detail.pk }} - {{ detail.title }}</h2>
    <p>{{ detail.description }}</p>
    <p class="text-end">{{ detail.date|date:'Y d M' }}</p>
    <a href="{% url 'blog:blog' %}" class="btn btn-info my-5">Вернуться</a>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2 class="text-center">Blogs</h2>
    {% for blog in blogs %}
    <div class="container">
        <a href="{% url 'blog:detail' blog.pk %}"><h1 class="text-center">{{ blog.title }}</h1></a>
        <p class='text-end'>{{ blog.date }}</p>
        <p>{{ blog.description|truncatechars:300 }}</p>
    </div>
    {% endfor %}
{% endblock %}

portfolio/templates/portfolio/detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <h2 class="text-center">{{ detail.title }}</h2>
    <img src="{{ detail.image.url }}" alt="{{ detail.title }}"  class="my-2"/>
    <p>{{ detail.description }}</p>
    {% if detail.url %}
    <a href="{{ detail.url }}" class="my-2">Перейти на сайт</a>
    {% endif %}
    <br/>
    <a href="{% url 'project:project' %}" class="btn btn-info my-5">Вернуться</a>
</div>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container"></div>
    <h2 class="text-center">My Projects</h2>
    <div class="d-flex justify-content-around row">
    {% for project in projects %}
        <div class="card col-auto mx-2" style="width: 18rem;">
            <a href="{% url 'project:project_detail' project.pk %}"><img src="{{ project.image.url }}" class="card-img-top" alt="{{ project.title }}"></a>
            <div class="card-body">
            <h5 class="card-title">{{ project.title }}</h5>
            <p class="card-text">{{ project.description|truncatechars:100 }}</p>
            {% if project.url %}
            <a href="{{ project.url }}" class="btn btn-primary">Go ...</a>
            {% endif %}
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}